#    We already have a secret key file beta.txt under /opt location on jump host. 
#    Create a secret named as beta and it should contain the password/license-number present 
#    in beta.txt file.
#
#    Also create a pod named as secret-datacenter.
#
#    Configure pod's spec as container name should be secret-container-datacenter, image should be 
#    ubuntu preferably with latest tag (remember to mention the tag with image). Use command '/bin/bash', '-c' 
#    and 'sleep 10000' for container. Mount a volume named as secret-volume-datacenter. 
#    The mount path should be /opt/games and mode should be readOnly.
#
#    Mount the secret within this volume.
#
#    To verify you can exec into the container secret-container-datacenter, to check the secret key 
#    under the mounted path /opt/games.
#
#    Secret type should be generic.
#
#Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.
---

#kubectl create secret generig beta --from-file=/opt/beta.txt
#
#

    
apiVersion: v1
kind: Pod
metadata:
    name: secret-datacenter
spec:
    containers:
    - name: secret-container-datacenter
      image: ubuntu:latest
      command: [ "/bin/bash"]
      args: ["-c", "sleep 10000"]
      volumeMounts:
      - name: secret-volume-datacenter
        mountPath: "/opt/games" 
        readOnly: true
    volumes:
    - name: secret-volume-datacenter
      secret:
        secretName: beta
